### ISSUE TITLE
issues with local storage?

### ISSUE THREAD

**Issue by brokosz** [beet/alfred_noteplan_actions#10]
I updated `base.rb` with the correct base path for local only storage `/⁨Library⁩/⁨Containers⁩/⁨co.noteplan.NotePlan⁩/⁨Data⁩/⁨Library⁩/⁨Application Support⁩/⁨co.noteplan.NotePlan⁩` but the only thing that seems to work is quick add of tasks. Are there other files that need to be touched for hashtags, note search and journal summary?

**Comment by beet** [comment]
Thanks raising the issue. That's interesting, on my machine the base path is `~/Library/Mobile Documents/iCloud~co~noteplan~NotePlan/Documents`, does that directory not exist on yours?

Maybe try making sure you have `/Documents` on the end, like:

```
/⁨Library⁩/⁨Containers⁩/⁨co.noteplan.NotePlan⁩/⁨Data⁩/⁨Library⁩/⁨Application Support⁩/⁨co.noteplan.NotePlan⁩/Documents
```

and see if that works.

The base directory should contain two subdirectories, Calendar and Notes:

```
$ ls -l ~/Library/Mobile\ Documents/iCloud~co~noteplan~NotePlan/
total 0
drwxr-xr-x  6 beet  staff  192 24 Sep 11:21 Documents

beet@MacBook-Pro-5 frontend $ ls -l ~/Library/Mobile\ Documents/iCloud~co~noteplan~NotePlan/Documents/
total 0
drwxr-xr-x  297 beet  staff   9504 24 Sep 10:34 Calendar
drwxr-xr-x  535 beet  staff  17120 24 Sep 11:21 Notes
```

If you do manage to find the correct directory, I could move it into workflow settings so you can change it without having to modify the contents.

**Comment by brokosz** [comment]
blurgh, that was my bad. I left `/Documents` off the end of the path… but when I add it I get the same behavior: no note/hashtag search, no Journal Summary function. An environment variable would be helpful for me so I'm not in editing the ruby file. 

I don't have the Mobile Documents path because iCloud Drive is disabled by admin policy. Local storage it is. Of course, it all works fine on my home machine setup for iCloud sync.

**Comment by brokosz** [comment]
I changed my NotePlan path in `base.rb` again and this works now.  no need to do anything here.

**Comment by beet** [comment]
👍
