### ISSUE TITLE
Extend 't' quick open action to open calendar files as well

### ISSUE THREAD

**Issue by jgclark** [beet/alfred_noteplan_actions#14]
I won't use this as often as opening a text note by its title, but why not allow it to search over calendar files by YYYYMMDD as well? 
I've had a look at the code, but again it's structured in a way I don't yet understand, so can't try this myself.

**Comment by beet** [comment]
Yeah, good idea, I found myself wanting to do this too, as Noteplan doesn't provide a native mechanism for jumping directly to a specific date, which can be cumbersome if it's more than a few weeks/months either side of the current date.

**Comment by beet** [comment]
@jgclark, I seem to have a solution for opening calendar notes, but it only works with existing notes and can't jump to dates that haven't had a note created yet.

If you're still interested, there's a pre-release available at https://github.com/beet/alfred_noteplan_actions/releases/tag/0.7.0-beta

**Comment by jgclark** [comment]
Excellent, thanks, @beet. I probably wouldn't ever want to open a calendar note that hadn't been created yet, so this is complete as far as I'm concerned.

**Comment by beet** [comment]
Finally got around to sorting out the 0.7.0 release, which includes the ability to open existing calendar notes.
