### ISSUE TITLE
wl deprecation

### ISSUE THREAD

**Issue by brokosz** [beet/alfred_noteplan_actions#21]
Not an issue, but for what it's worth - I sometimes edit my NotePlan notes with other apps (most notably Typora and nvUltra) so having quick access to add a NotePlan style wiki link via Alfred is something I still use. Typora doesn't support them, and nvUltra links the filename not the header: `[[my_great_note]]` resolves to `my_great_note.txt` (which isn't ideal). It would be great if you still leave this feature in (at least, for my workflow).

**Comment by beet** [comment]
👍 Agreed, I've also noticed that NotePlan's native auto-completion breaks on spaces, so I'll be keeping this one for the foreseeable future, as Alfred's script filter fuzzy-matching is very powerful.
