### ISSUE TITLE
Changing the file extension

### ISSUE THREAD

**Issue by jimmystuart** [beet/alfred_noteplan_actions#23]
Would it be possible to add a configurable variable to the alter the file extension from txt to say md? With the latest NP3 Beta, a feature was introduced to change the file extension used so that the markdown files could be used with other editors more easily that are expecting a .md file extension (such as Obsidian). 

Thanks!!

**Comment by brokosz** [comment]
it looks straightforward... I changed two lines in `lib\note+plan\base.rb` to see if it was a simple mod and everything is working fine for me.

**Comment by brokosz** [comment]
Changing lines 29 and 35 of `alfred_noteplan_actions/lib/note_plan/base.rb` from `.txt` to `.{txt,md}` is a quick fix to cover what I assume is going to be common, but isn't as infinitely configurable as a true user variable would be.
