### ISSUE TITLE
text search not working

### ISSUE THREAD

**Issue by jbucchieri** [beet/alfred_noteplan_actions#28]
I am a relatively new at workflow actions in Alfred.  Can't seem to get the text search working.  The "q" command working fine.  I did change the file location in the settings. everything else is the same.

**Comment by cschellhas** [comment]
Same Problem here.

**Comment by joshdoyle** [comment]
I am having this same problem. "Q" works fine but text search doesn't. Changing the Alfred filter as cschellhas recommended did not help me.

**Comment by beet** [comment]
So, some stuff happened over the last couple of years.... but finally got around to fixing the quick-open action, which should now work with subdirectories and the awesome new weekly/monthly/yearly notes.

The 1.0.0 release is set to not export the workflow variables, oh, which reminds me there's another snippet action for inserting time block strings I forgot to mention.

https://github.com/beet/alfred_noteplan_actions/releases/tag/1.0.0
